### ISSUE TITLE
Is there a need for multi-resource selectors?

### ISSUE THREAD

**Issue by iherman** [w3c/publ-loc#11]
The definition is complex, and we have to be sure that the selector really has reasonable use cases. Selection of _2_ consecutive resources is covered by the usage of the Embedded Resource Selector (combined with refinement).

**Comment by RachelComerford** [comment]
An example of this would be in educational publishing - summative assessment is meant to bring together concepts tackled across different areas of the text to allow students to connect them and draw conclusions. To provide a student with a hint, a reference, or feedback that includes the original publication, the publisher may need to link to multiple, non-consecutive xhtml files.

**Comment by iherman** [comment]
@RachelComerford thanks! Just for my understanding, this means that the selection is not necessarily a consecutive range of slections (ie, some sort of a long interval across several files) but, possibly, a link of several selections (ie, a bit of text from a bunch of files). 

It may be helpful if we could write that in a slightly more detailed example like the other ones we have for each selector in the [document itself](https://w3c.github.io/publ-loc/#MultiResourceSelector_def). Can you give us a short paragraph?

Thanks!!

**Comment by RachelComerford** [comment]
@iherman something like this?

Example Use Case: Rachel is writing a summative assessment question with hints pointing back to the textbook. The questions pulls on material presented in Chapter 2, a-head 3 and in Chapter 5, a-head 2.  She would like a single link to add to the hints section of her assessment questions that references Sections 2.3 and section 5.2 but nothing in between them.

**Comment by iherman** [comment]
@RachelComerford that is perfect; I have taken over in PR #20, though I made it slightly more complicated by adding a third reference (to make it clear that MRS really means 'multi', not only two...)

However... this example raises new problems for #10 …

**Comment by iherman** [comment]
Closing by virtue of merging #23. More specific issues have also been added for further discussion: #24, #25, and #26.
