### ISSUE TITLE
Relationship to Web Annotations

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/publ-loc#18]
Even though it is discussed throughout the document, I think it would be valuable to have a short appendix called "Relationship to Web Annotations". This will clarify that this is an addendum not a fork and why this document is necessary. (See https://www.w3.org/TR/appmanifest/#relationship-to-html's-link-and-meta-elements for a lengthy example.)

**Comment by iherman** [comment]
I agree. I will add a subsection, though, at this moment, I would prefer to leave it empty (ie, just a placeholder) and fill it when we are in the clear of which extensions we really add.

**Comment by iherman** [comment]
Added this in PR #19. Issue can be closed when the PR is merged.
