### ISSUE TITLE
Is the modeling of the new Embedded Resource Selector consistent?

### ISSUE THREAD

**Issue by iherman** [w3c/publ-loc#24]
Is the modeling of the new Embedded Resource Selector consistent with (i.e., a reasonable additional type of) the Selector class as defined by Web Annotations? 

(Taken over from @tcole3’s [comment](https://github.com/w3c/publ-loc/pull/23#issuecomment-341295925))

**Comment by iherman** [comment]
> I would argue it is. In example 10 you have a resource (MobyDick.wpub, a Web Publication) and you want to identify and reference a segment of it that happens to have it's own URL (moby-dick-book-cover.jpg). To me the fact that the segment has its own URL does not invalidate using a Selector to reference it, but this is arguable and needs to be discussed.

(From @tcole3’s [comment](https://github.com/w3c/publ-loc/pull/23#issuecomment-341295925))

**Comment by iherman** [comment]
I must admit I do not see a problem with ERS as a Selector...

**Comment by Treora** [comment]
One more thought, I forgot to add [here](https://github.com/w3c/publ-loc/issues/10#issuecomment-341393404): EmbeddedResourceSelector seems a most generic type of selector for any hypermedia documents (anything supporting some form of transclusion, I guess). It may be worth specifying it with a broader use in mind than WebPublications. For example, I could target an image in a document by its URL.

One situation I am thinking of is the case where specifying a URL is ambiguous: e.g. a document contains the same image twice. Just saying `{"type": "EmbeddedResourceSelector", "value": "example.org/image"}` may thus yield two results. Of course, another (document type-specific) selector could be used instead to point to the right instance (e.g. an XPathSelector), but it may be worth keeping the situation in mind.

Thinking this way, I wonder about other ways to point at embedded resources, by describing their relative relation to the document. If the link has a `name`, referring to that name may be a desirable way to point at the subresource it links to (somewhat like a path an IPFS URL). In fact, [FragmentSelector](https://www.w3.org/TR/2017/REC-annotation-model-20170223/#fragment-selector) may already serve this purpose quite well.

**Comment by tcole3** [comment]
@Treora concern is orthogonal and has been opened as a new issue.

Otherwise satisfied that ERS is consistent with the Selector model, so closing this issue.
