### ISSUE TITLE
rename the document

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/publ-loc#38]
Proposals include Web Annotation for Web Publications, An Extension to Web Annotations, and other things involving the word "Annotations". Please submit recommendations for names by Wednesday 13 December.

**Comment by mattgarrish** [comment]
Based on the call, and looking at s. 2, do we want a combination of the two:

Web Annotation Extensions for Web Publications ?

**Comment by WSchindler** [comment]
I would stick to **"Locators for Web Publications"**. 

The Oxford Online English Dictionary  defines a **locator** as "_A device or system for locating something, ..._" [https://en.oxforddictionaries.com/definition/locator](url) and **locate** as "_Discover the exact place or position of._"[https://en.oxforddictionaries.com/definition/locate](url). Merriam-Webster defines **locate** primarily as "_to determine or indicate the place, site, or limits of_ " [https://www.merriam-webster.com/dictionary/locating](url).

I see that the Web Annotation Model has a much broader concept of an  **annotation** than I would typically expect. For me an "annotation" is a kind of comment attached to a particular part of a resource. This is IMO only one use case for our locators.

We need different approaches to be able to point to a specific part of an information resource. The location and scope of that part have to be defined. I personally think that subsuming this referencing mechanism under web annotations may be technically correct, but that this term may be difficult to be understood correctly by editors or authors.

**Comment by baldurbjarnason** [comment]
Based on how much energy EPUBCFI sucked up from content producers who, fruitlessly, kept trying to use it in content production, I find the use of 'locator' in the document's title highly problematic. 

Irrespective of definitions, 'locator' implies a much more general purpose mechanism than this spec will ever provide in practice.

"Web Annotation Extensions for Web Publications" is at least factually descriptive without implying a scope that's greater than it's actually providing.

**Comment by iherman** [comment]
My reservation with the title "Web Annotation Extensions for Web Publications" is that it promises more than we ever plan to deliver. The Web Annotation spec(s) includes much more than just the Selector+State mechanism that we call "Locator". It includes details on (JSON) structure for annotations in general, it includes an HTTP Protocol to exchange annotations, etc. 

This document does not, and I do not think will ever _extend_ the Web Annotation specs as a whole. It just extend the extension mechanism.

"Annotation Selector Extensions for Web Publications" would be a much more precise title, except that the current document also includes the term "Position" which, strictly speaking, is disjoint to selectors. But may still be closer to reality than "Web Annotation Extensions...".

**Comment by tcole3** [comment]
I would propose, "Web Publication Extensions of Web Annotations Data Model".

The Web Annotation Data Model (and Vocabulary by reference with regard to extensions) explicitly allows for extension with new classes and properties. We are adding a new classes of specifiers, some with new properties. Positions are simply a new class of what the Web Anno model terms (informally) specifiers. 

I do not believe that this title commits us to do more than extend specifiers. It does not imply that we will extend all parts of the WA data model, only what we think is necessary for the Web Publication use case. And it does give us room should we later find a need to extend more than just specifiers.

**Comment by iherman** [comment]
@tcole3 

> I do not believe that this title commits us to do more than extend specifiers. It does not imply that we will extend all parts of the WA data model, only what we think is necessary for the Web Publication use case. And it does give us room should we later find a need to extend more than just specifiers.

You are right it does not formally commits us, but it surely can be understood that way. That is what bothers me.

"Web Publication Extensions of Web Annotations Selections"

With a short name of 

"wpub-sel"

?

**Comment by TzviyaSiegman** [comment]
@iherman "Web Publication Extensions of Web Annotations Selections" does not roll off the tongue, but it does get all the information into one title. So +1

**Comment by iherman** [comment]
@tcole3 @mattgarrish @BigBlueHat ? I am not fond of that title either, but I do not see any better:-( 

However... to move on, make the documents ready to go and ask for a FPWD we should have the name fixed this week...

**Comment by BigBlueHat** [comment]
@iherman I fear we're being overly prescriptive in the naming and attempting to name the document based on what's written there, and not one what (likely) should be written there in the future.

To me, "Web Annotation Extensions for Web Publications" has the most promise about what will be in the document and is a name "big enough" to hold other related items which may need to be added there later--while also avoiding tangling things around the contested word "selectors" (or locators or selections or...).

So, my preference would be for: "Web Annotation Extensions for Web Publications"

**Comment by iherman** [comment]
@BigBlueHat, we also need a short name. In case your proposal is accepted, what should that be? I would propose “wpub-ann”.

**Comment by tcole3** [comment]
I'm neutral among the latest options, but I would note that while "Selectors" is normatively defined, "Selection" does not appear to be normatively defined. At least not yet. In Selectors 3 Rec, selection is lower case and not anywhere defined, nor is it really claimed as such in the Shadow DOM documents (though it is a little fuzzier there). There a Selection API Working Draft up from earlier in the summer (which is interesting in several particulars), but at some point, this all gets pedantic. I would be fine with "Web Publication Extensions of Web Annotations Selections"

**Comment by mattgarrish** [comment]
I'm turned off by "selections", to be honest. The selection is not what does the selecting, so it doesn't really solve the problem of what we call the selector that shall not be named selector.

**Comment by TzviyaSiegman** [comment]
We don't seem to have consensus. I recommend that we move forward with "Web Annotation Extensions for Web Publications" with a short name "wpub-ann" because that got 2 votes.

**Comment by iherman** [comment]
Closing the issue, the rename happens per [tzviya's comment](https://github.com/w3c/wpub-ann/issues/38#issuecomment-351998027)
